import { Injectable, NotFoundException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { tr } from "../../i18n/translate";
import { AttachmentStorageProvider } from "./attachment-storage.interface";
import { assertSafeStorageKey } from "./storage-key.util";

/**
 * Stores attachment bytes in S3-compatible object storage. Chosen by
 * ATTACHMENT_STORAGE_PROVIDER=s3.
 *
 * Works with AWS S3 and any S3-compatible service (MinIO, Cloudflare R2,
 * Backblaze B2, ...) via ATTACHMENT_S3_ENDPOINT / ATTACHMENT_S3_FORCE_PATH_STYLE.
 * Credentials come from ATTACHMENT_S3_ACCESS_KEY_ID / _SECRET_ACCESS_KEY when
 * set, otherwise from the default AWS credential chain (instance role, env, ...).
 *
 * The client is built lazily on first use so a deployment that never selects s3
 * pays nothing and never needs the bucket configured. As with the local provider,
 * bytes live outside the database but DO travel in an application backup: the
 * export reads each object and carries it base64-encoded in `attachment_blobs`,
 * and a restore stages it back through this provider -- so the bucket does not
 * have to be backed up separately.
 *
 * An artifact exported before that change carries only metadata, and
 * restoring one needs more than this store: the bytes are read from the CURRENT
 * instance and only after it confirms the user already owns a matching
 * `transaction_attachments` row (same id, provider, size, SHA-256), so on a fresh
 * instance every external attachment is skipped however faithfully the store was
 * restored.
 */
@Injectable()
export class S3StorageProvider implements AttachmentStorageProvider {
  readonly name = "s3";

  private clientInstance?: S3Client;
  private readonly bucket: string;
  private readonly prefix: string;

  constructor(private readonly config: ConfigService) {
    this.bucket = this.config.get<string>("ATTACHMENT_S3_BUCKET") ?? "";
    const prefix = this.config.get<string>("ATTACHMENT_S3_PREFIX") ?? "";
    // Normalise to at most one trailing slash so object keys join cleanly.
    this.prefix = prefix ? `${prefix.replace(/\/+$/, "")}/` : "";
  }

  private client(): S3Client {
    if (this.clientInstance) return this.clientInstance;
    if (!this.bucket) {
      throw new Error(
        "ATTACHMENT_S3_BUCKET must be set when ATTACHMENT_STORAGE_PROVIDER=s3",
      );
    }
    const endpoint = this.config.get<string>("ATTACHMENT_S3_ENDPOINT");
    const accessKeyId = this.config.get<string>("ATTACHMENT_S3_ACCESS_KEY_ID");
    const secretAccessKey = this.config.get<string>(
      "ATTACHMENT_S3_SECRET_ACCESS_KEY",
    );
    const forcePathStyle =
      (this.config.get<string>("ATTACHMENT_S3_FORCE_PATH_STYLE") ?? "")
        .toLowerCase()
        .trim() === "true";

    this.clientInstance = new S3Client({
      region: this.config.get<string>("ATTACHMENT_S3_REGION") ?? "us-east-1",
      ...(endpoint ? { endpoint } : {}),
      forcePathStyle,
      ...(accessKeyId && secretAccessKey
        ? { credentials: { accessKeyId, secretAccessKey } }
        : {}),
    });
    return this.clientInstance;
  }

  /**
   * The bucket key for an attachment key.
   *
   * Validated, because the key is not necessarily server-generated by the time
   * it gets here: a restore writes `storage_key` from an uploaded backup file.
   * Unvalidated, this took whatever that file said straight into
   * `GetObject`/`PutObject` -- addressing arbitrary objects in the bucket, and
   * outside `ATTACHMENT_S3_PREFIX` too, since an S3 prefix is a naming
   * convention and not a boundary. `LocalStorageProvider` had this check; this
   * provider did not.
   */
  private objectKey(key: string): string {
    return `${this.prefix}${assertSafeStorageKey(key)}`;
  }

  async save(key: string, data: Buffer): Promise<void> {
    await this.client().send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: this.objectKey(key),
        Body: data,
      }),
    );
  }

  async load(key: string): Promise<Buffer> {
    try {
      const result = await this.client().send(
        new GetObjectCommand({
          Bucket: this.bucket,
          Key: this.objectKey(key),
        }),
      );
      const body = result.Body;
      if (!body) {
        throw new NotFoundException(
          tr("errors.attachments.notFound", "Attachment not found"),
        );
      }
      const bytes = await body.transformToByteArray();
      return Buffer.from(bytes);
    } catch (error) {
      if (this.isNotFound(error)) {
        throw new NotFoundException(
          tr("errors.attachments.notFound", "Attachment not found"),
        );
      }
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    // S3 DeleteObject is already idempotent -- deleting a missing key succeeds.
    await this.client().send(
      new DeleteObjectCommand({
        Bucket: this.bucket,
        Key: this.objectKey(key),
      }),
    );
  }

  private isNotFound(error: unknown): boolean {
    const e = error as {
      name?: string;
      $metadata?: { httpStatusCode?: number };
    };
    return (
      e?.name === "NoSuchKey" ||
      e?.name === "NotFound" ||
      e?.$metadata?.httpStatusCode === 404
    );
  }
}
